FROM node:18-alpine as build

WORKDIR /frontend

COPY . .

RUN npm ci
RUN npm run build


FROM nginx:1.23.1-alpine
EXPOSE 80
COPY ./docker/nginx/conf.d /etc/nginx/conf.d/default.conf
COPY --from=build /frontend/dist /usr/share/nginx/html